# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SquidAnalyzer
version:      4.3
version_from: SquidAnalyzer.pm
installdirs:  site
requires:
    GD:                            0
    GD::Graph:                     0
    GD::Graph3d:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
