# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SquidAnalyzer
version:      5.1
version_from: SquidAnalyzer.pm
installdirs:  site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
